[package]
name = "rust_admob_ssv"
version = "0.1.0"
authors = ["Tim Serowski <info@timserowski.de>"]
edition = "2018"

[dependencies]
base64 = "0.12"
data-encoding = "2"
urlparse = "0.7"
openssl = "0.10"
sha2 = "0.8"